# Generated by Django 3.1.8 on 2021-04-19 17:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pancakeimage_pancakepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancakeimage',
            name='pancake_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pancake_images', to='content.pancakepage'),
        ),
    ]
