# Generated by Django 3.1.8 on 2021-04-19 19:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_aircraftimage_aircraftpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftimage',
            name='page',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_images', to='content.aircraftpage'),
            preserve_default=False,
        ),
    ]
