# Generated by Django 3.1.8 on 2021-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_airportpage_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimages',
            name='button_text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
